completed css-brochure-form. Paul Son
contactpaulson/c1121-code-solutions pull request #15
Opened 2021-12-02 09:22 UTC by contactpaulson

![css-brochure-form](https://user-images.githubusercontent.com/93624324/144393694-bd6dbe6f-63d0-47fc-b625-3585d86e737b.png)

2021-12-02 18:52 UTC, codingcodymiller requested changes
Hey Paul, the width of your form is too wide as compared to the example, please revise and resubmit with a new screenshot

2021-12-02 19:16 UTC, contactpaulson commented
![css-brochure-form](https://user-images.githubusercontent.com/93624324/144488101-36056f7c-f918-4553-b5dd-a8a387ef75a5.png)

2021-12-02 20:24 UTC, codingcodymiller requested changes

2021-12-02 20:24 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-left: 875px;
Hey dude! Please fix this margin, as we discussed 🤓

2021-12-03 06:23 UTC, contactpaulson commented
![css-brochure-form](https://user-images.githubusercontent.com/93624324/144555535-084a74dc-7d5c-4562-844e-8bb0ef371fc2.png)

2021-12-03 06:35 UTC, contactpaulson commented
![css-brochure-form](https://user-images.githubusercontent.com/93624324/144556738-cd2eab89-b6db-4f33-bbd8-740ae99c983a.png)

2021-12-03 17:02 UTC, codingcodymiller requested changes

2021-12-03 17:02 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-left: 297px;
You can remove all this and just do `text-align: right` as we discussed

2021-12-03 22:55 UTC, contactpaulson commented
![css-brochure-form](https://user-images.githubusercontent.com/93624324/144683311-a403cf01-a676-4c93-a2e4-cd53fdc4961f.png)

2021-12-03 23:04 UTC, codingcodymiller approved these changes
Great work!!

2021-12-04 00:45 UTC, merged