completed javascript-functions.
contactpaulson/c1121-code-solutions pull request #27
Opened 2021-12-07 23:43 UTC by contactpaulson

![javascript-functions](https://user-images.githubusercontent.com/93624324/145123014-2afcfb69-99ef-4cfc-997c-be9dc95e16bb.png)

2021-12-07 23:46 UTC, codingcodymiller requested changes

2021-12-07 23:46 UTC, codingcodymiller commented on javascript-functions/main.js
> +}
You shouldn't `console.log` the output inside the function, you should `return` the final output of the function, and you can log it where the function is called.

2021-12-08 00:18 UTC, contactpaulson commented
![javascript-functions](https://user-images.githubusercontent.com/93624324/145125935-362bd88f-67d9-4dc5-bb2a-76bd89fd49d3.png)

2021-12-08 17:20 UTC, codingcodymiller approved these changes

2021-12-08 17:49 UTC, merged