completed css-canvas-medical. Paul Son
contactpaulson/c1121-code-solutions pull request #28
Opened 2021-12-08 15:24 UTC by contactpaulson

![css-canvas-medical 1](https://user-images.githubusercontent.com/93624324/145234846-424d8578-d268-43b8-abfe-5293fa49a8fd.png)
![css-canvas-medical 2](https://user-images.githubusercontent.com/93624324/145234866-60011b3e-a96f-4413-9833-5dd8912fb20d.png)
![css-canvas-medical 3](https://user-images.githubusercontent.com/93624324/145234874-59ff25f0-4d89-40c8-9552-5b94e4d82957.png)

2021-12-08 18:10 UTC, codingcodymiller requested changes
Hey Paul! It looks like your overlay on the hero image is covering the text and button, that is not the way it is meant to be set up, the content should be above the overlay. Please revise and submit a new screenshot with your revision.

2021-12-09 03:27 UTC, contactpaulson commented
![css-canvas-medical 4](https://user-images.githubusercontent.com/93624324/145329144-4b981fbe-c1ba-483c-a479-78555272ec1d.png)

2021-12-09 20:43 UTC, codingcodymiller requested changes
Hey Paul! The "Contact Us" link in the navbar just looks like a normal link, but in the example, it is styled to look like a button, please revise and submit a new screenshot when you have committed your changes.

2021-12-10 05:30 UTC, contactpaulson commented
![css-canvas-medical 5](https://user-images.githubusercontent.com/93624324/145522346-6da33b73-6d3d-4bd8-8dba-dfdfb5435051.png)

2021-12-10 23:00 UTC, codingcodymiller requested changes

2021-12-10 23:00 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  display: flex;
Instead of applying `display: flex` here, could this element be a `row`?

2021-12-10 23:00 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  display: flex;
Instead of applying `display: flex` here, could this element be a `row`?

2021-12-10 23:00 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  display: flex;
Instead of applying `display: flex` here, could this element be a `row`?

2021-12-10 23:00 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  display: flex;
Instead of applying `display: flex` here, could this element be a `row`?

2021-12-13 18:23 UTC, codingcodymiller approved these changes
Great work!!

2021-12-13 19:28 UTC, merged