completed javascript-if exercise. Paul Son
contactpaulson/c1121-code-solutions pull request #30
Opened 2021-12-08 23:09 UTC by contactpaulson

![javascript-if](https://user-images.githubusercontent.com/93624324/145305673-ae2d44ff-fa8e-4e56-ab51-aa85fe94f3ea.png)

2021-12-08 23:25 UTC, codingcodymiller requested changes

2021-12-08 23:25 UTC, codingcodymiller commented on javascript-if/main.js
> +  }
You can just `return false` here, you are never old enough to drink and drive 👮

2021-12-08 23:35 UTC, contactpaulson commented
![javascript-if](https://user-images.githubusercontent.com/93624324/145308009-186665f5-ae54-47e3-907c-2978d4dc5807.png)

2021-12-08 23:39 UTC, codingcodymiller requested changes

2021-12-08 23:39 UTC, codingcodymiller commented on javascript-if/main.js
> +  }
Now it would only work if you are given an age of `null` 😂 . The code block can just be `return false`

2021-12-09 19:58 UTC, codingcodymiller approved these changes

2021-12-09 20:31 UTC, merged