completed javascript-loops-practice. Paul Son
contactpaulson/c1121-code-solutions pull request #35
Opened 2021-12-10 16:51 UTC by contactpaulson

![javascript-loops-practice 1](https://user-images.githubusercontent.com/93624324/145611197-92fdd122-0228-4313-a605-42e4b2563b12.png)
![javascript-loops-practice 2](https://user-images.githubusercontent.com/93624324/145611215-52852fc6-5328-40f2-b8fa-dfe0d788e343.png)

2021-12-10 22:54 UTC, codingcodymiller requested changes

2021-12-10 22:54 UTC, codingcodymiller commented on javascript-loops-practice/get-student-names.js
> +  for (var key in students) {
`students` is an array, you should use a `for` loop.

2021-12-11 04:32 UTC, contactpaulson commented
![javascript-loops-practice revised](https://user-images.githubusercontent.com/93624324/145663812-afc647cd-e5d8-46df-9fa2-585bf7439f7c.png)

2021-12-13 18:32 UTC, codingcodymiller approved these changes

2021-12-13 19:29 UTC, merged